target 'LocationSearch' do
  use_frameworks!

  # Define the global platform we support
  platform :ios, '9.0'
 
  # Silent warnings from all pods
  inhibit_all_warnings!

  # Pods for LocationSearch
  pod 'ObjectMapper', '~> 2.2'
  pod 'Alamofire', '~> 4.2.0'
  pod 'AlamofireObjectMapper', '~> 4.0'
  pod 'OHHTTPStubs', '~> 5.2.1'
  pod 'OHHTTPStubs/Swift', '~> 5.2.1'

  target 'LocationSearchTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
